name: flutter_app
description: Mixin Messenger
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.41.0+133

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  android_id: ^0.3.6
  ansicolor: ^2.0.1
  archive: ^3.4.6
  async: ^2.8.1
  audio_session: ^0.1.16
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  blurhash_dart: ^1.0.2
  bring_window_to_front:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 904786942d698d103ef1f27b5e9331c6a6ec8a37
      path: packages/bring_window_to_front
  common_crypto:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 1ac0384083ca7d072f9d1246a0dd221e458d3169
      path: packages/common_crypto
  dbus: ^0.7.8
  decimal: ^2.3.3
  desktop_drop:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: a8e2bab0447760eb09457eafbc49e8d7c8cbb99f
      path: packages/desktop_drop
  desktop_keep_screen_on: ^0.0.2
  desktop_webview_window: ^0.2.3
  device_info_plus: ^9.0.3
  dio: ^5.3.3
  dio_smart_retry: ^5.0.0
  drift: ^2.11.1
  ecache: ^2.0.2
  emojis: ^0.9.9
  equatable: ^2.0.5
  file_picker: ^5.5.0
  file_selector: ^1.0.1
  file_selector_linux: ^0.9.0
  file_selector_macos: ^0.9.3
  file_selector_windows: ^0.9.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_app_icon_badge: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.7
  gallery_saver: ^2.3.2
  github: ^9.19.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  hooks_riverpod: ^2.4.3
  http: ^0.13.6
  http_client_helper: ^2.0.3
  hydrated_bloc: ^9.1.2
  image: ^4.1.3
  image_picker: ^1.0.4
  intl: ^0.18.0
  intl_phone_number_input: ^0.7.3+1
  isolate: ^2.1.0
  json_annotation: ^4.8.1
  libsignal_protocol_dart: ^0.7.0
  local_auth:
    git:
      url: https://github.com/YeungKC/packages
      ref: 69bab28cda3bd948f0db5ad7fc9831c29fdcf400
      path: packages/local_auth/local_auth
  lottie: ^2.6.0
  map: ^1.4.2
  markdown_widget: ^2.3.1
  mime: ^1.0.2
  mixin_bot_sdk_dart: ^0.4.1
  mixin_logger: ^0.1.0
  native_dio_adapter: ^0.1.0
  network_info_plus: ^4.1.0
  octo_image: ^2.0.0
  ogg_opus_player: ^0.7.0
  open_file:
    git:
      url: https://github.com/crazecoder/open_file.git
      ref: fbf68e4bb5cb3e262d8f8ebe10b2f8449ff8e030
  overlay_support: ^2.1.0
  package_info_plus: ^4.2.0
  path: ^1.8.0
  path_provider: ^2.1.1
  photo_view:
    git:
      url: https://github.com/fireslime/photo_view.git
      ref: 52685ab7beaf8a9107904bdb8a1590924015d016
  pin_code_fields: ^8.0.1
  platform_device_id: ^1.0.1
  pretty_qr_code: ^3.0.0
  protocol_handler: ^0.1.5
  provider: ^6.0.4
  quick_breakpad:
    path: third_party/quick_breakpad
  recase: ^4.1.0
  rxdart: ^0.27.5
  scrollable_positioned_list: ^0.3.5
  simple_animations: ^5.0.2
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.17
  stream_transform: ^2.1.0
  string_tokenizer:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      path: packages/string_tokenizer
      ref: 0334bbaa7293c72398eaf4571ba7ba2b5df2302d
  super_clipboard: 0.6.4
  super_context_menu: ^0.6.4
  super_native_extensions: ^0.6.4
  synchronized: ^3.0.1
  system_tray:
    path: third_party/system_tray
  ui_device:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 00654e51f51aa65cdc39784a3075c9abb8b9dd7c
      path: packages/ui_device
  ulid: ^2.0.0
  url_launcher: ^6.1.14
  uuid: ^3.0.4
  very_good_analysis: ^5.1.0
  visibility_detector: ^0.4.0+2
  watcher: ^1.1.0
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.4.1
  win32: ^5.0.9
  win_toast: ^0.3.0
  window_manager: ^0.3.7
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6
  debug_info_collector:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 77f03330001941f0ac303de6276dd2380f5bcc7e
      path: packages/debug_info_collector
  drift_dev: ^2.12.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  intl_utils: ^2.8.5
  json_serializable: ^6.7.1
  msix: ^3.16.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  # assets end

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: fonts/Noto-COLRv1.ttf

flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: false

analyzer:
  plugins:
    - moor

msix_config:
  display_name: Mixin Desktop
  publisher_display_name: Mixin Ltd
  identity_name: 14801MixinLtd.MixinDesktop
  publisher: CN=272248D5-9A62-44D7-A299-5E1F8B46A9B0
  msix_version: 0.38.0.0
  logo_path: ./assets/icons/windows_app_icon.png
  vs_generated_images_folder_path: ./dist/icons
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,microphone'
  store: true
  toast_activator:
    clsid: "94B64592-528D-48B4-B37B-C82D634F1BE7"
    arguments: "-ToastActivated"
    display_name: "Mixin Messenger"
