name: flutter_app
description: Mixin Messenger
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.38.5+56

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  android_id: ^0.1.3
  ansicolor: ^2.0.1
  archive: ^3.3.2
  async: ^2.8.1
  bloc: ^8.1.0
  blurhash_dart: ^1.0.2
  bring_window_to_front:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 904786942d698d103ef1f27b5e9331c6a6ec8a37
      path: packages/bring_window_to_front
  dbus: ^0.7.8
  decimal: ^2.3.2
  desktop_drop: ^0.4.1
  desktop_lifecycle: ^0.1.0
  desktop_webview_window: ^0.2.0
  device_info_plus: ^8.0.0
  dio: ^5.0.0
  drift: 2.5.0
  ecache: ^2.0.2
  emojis: ^0.9.9
  equatable: ^2.0.5
  file_picker: ^5.2.3
  file_selector: ^0.9.2
  file_selector_linux: ^0.9.0
  file_selector_macos: ^0.9.0
  file_selector_windows: ^0.9.1
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_app_icon_badge: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.6
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.3
  flutter_svg: ^2.0.0+1
  gallery_saver: ^2.3.2
  github: ^9.9.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  http: ^0.13.5
  http_client_helper: ^2.0.3
  hydrated_bloc: ^9.0.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.2
  isolate: ^2.1.0
  json_annotation: ^4.7.0
  libsignal_protocol_dart: ^0.6.5
  lottie: ^2.1.0
  map: ^1.3.3
  markdown_widget: ^2.0.0+1
  mime: ^1.0.2
  mixin_bot_sdk_dart: ^0.3.15
  mixin_logger: ^0.0.3
  octo_image: ^1.0.2
  ogg_opus_player: ^0.7.0
  open_file:
    git:
      url: https://github.com/crazecoder/open_file.git
      ref: fbf68e4bb5cb3e262d8f8ebe10b2f8449ff8e030
  overlay_support: ^2.1.0
  package_info_plus: ^3.0.1
  pasteboard:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 7909b17640c06e9bf91b68e1e52105c3b16af284
      path: packages/pasteboard
  path: ^1.8.0
  path_provider: ^2.0.11
  photo_view:
    git:
      url: https://github.com/fireslime/photo_view.git
      ref: 52685ab7beaf8a9107904bdb8a1590924015d016
  pin_code_fields: ^7.4.0
  platform_device_id: ^1.0.1
  protocol_handler: ^0.1.4
  provider: ^6.0.4
  qr_flutter: ^4.0.0
  quick_breakpad:
    path: third_party/quick_breakpad
  recase: ^4.1.0
  rxdart: ^0.27.5
  scrollable_positioned_list: ^0.3.5
  sliver_tools: ^0.2.9
  sqlite3_flutter_libs: ^0.5.12
  stream_transform: ^2.1.0
  system_tray:
    path: third_party/system_tray
  tuple: ^2.0.1
  ui_device:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 00654e51f51aa65cdc39784a3075c9abb8b9dd7c
      path: packages/ui_device
  ulid: ^2.0.0
  url_launcher: ^6.1.8
  uuid: ^3.0.4
  very_good_analysis: ^3.1.0
  visibility_detector: ^0.3.3
  watcher: ^1.0.2
  web_socket_channel: ^2.2.0
  webview_flutter: ^4.0.4
  win32: ^3.1.2
  win_toast: ^0.3.0
  window_manager: ^0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1


dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.4.0
  debug_info_collector:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 393b52040e982ee1a31169f86face252701907ee
      path: packages/debug_info_collector
  drift_dev: 2.5.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  intl_utils: ^2.8.1
  json_serializable: ^6.6.0
  msix: ^3.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by https://github.com/fluttercandies/assets_generator
    # **************************************************************************

    - assets/
    - assets/icons/
    - assets/images/

  # assets end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: false

analyzer:
  plugins:
    - moor

msix_config:
  display_name: Mixin Desktop
  publisher_display_name: Mixin Ltd
  identity_name: 14801MixinLtd.MixinDesktop
  publisher: CN=272248D5-9A62-44D7-A299-5E1F8B46A9B0
  msix_version: 0.38.0.0
  logo_path: ./assets/icons/windows_app_icon.png
  vs_generated_images_folder_path: ./dist/icons
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,microphone'
  store: true
  toast_activator:
    clsid: "94B64592-528D-48B4-B37B-C82D634F1BE7"
    arguments: "-ToastActivated"
    display_name: "Mixin Messenger"
