name: flutter_app
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mixin_bot_sdk_dart:
    git:
      url: https://github.com/MixinNetwork/mixin_bot_sdk_dart.git
      ref: a04b8858189cf95ba868116ed81e0f7eca3e695a
#         local path
#    path: ../mixin_bot_sdk_dart
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 57a2cd88486105d3d813583339eb0e23c9bfd6d2
  http: ^0.13.3
  qr_flutter: ^4.0.0
  uuid: ^3.0.4
  ulid: ^2.0.0
  web_socket_channel: ^2.1.0
  moor: ^4.3.0
  sqlite3_flutter_libs: ^0.4.2
  libsignal_protocol_dart:
    git:
        url: https://github.com/MixinNetwork/libsignal_protocol_dart.git
        ref: a568152726b205534aee60d2971b05f69bd8801d
  path_provider: ^2.0.1
  path: ^1.8.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  cached_network_image: ^3.0.0
  very_good_analysis: ^2.0.3
  #  desktop_window: ^0.4.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  tuple: ^2.0.0
  archive: ^3.1.2
  hydrated_bloc: ^7.0.0
  rxdart: ^0.27.0
  json_annotation: ^4.0.1
  provider: ^5.0.0
  isolate: ^2.0.3
  dio: ^4.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  recase: ^4.0.0
  file_selector: ^0.8.2
  # file_selector_platform_interface: ^1.0.3+1
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  file_selector_linux: ^0.0.2
  mime: ^1.0.0
  url_launcher: ^6.0.1
  filesize: ^2.0.1
  flutter_portal: ^0.4.0
  flutter_markdown: ^0.6.2
  markdown: ^4.0.0
  map: ^0.3.0
  flutter_local_notifications: ^5.0.0+4
  flutter_app_icon_badge: ^2.0.0
  flutter_hooks: ^0.17.0
  package_info: ^2.0.0
  sliver_tools: ^0.2.2
  photo_view: ^0.11.1
  lottie: ^1.0.1
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner:
  hive_generator: ^1.1.0
  moor_generator: ^4.3.0
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/

  # assets end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: true

analyzer:
  plugins:
    - moor
