name: flutter_app
description: Mixin Messenger
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+430

environment:
  sdk: "^3.7.0"

dependencies:
  android_id: ^0.4.0
  ansicolor: ^2.0.3
  archive: ^4.0.7
  async: ^2.8.1
  audio_session: ^0.2.2
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  blurhash_dart: ^1.0.2
  bring_window_to_front:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 904786942d698d103ef1f27b5e9331c6a6ec8a37
      path: packages/bring_window_to_front
  common_crypto:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: af28658a415cf89383e3c9cf9f8230c79be5566c
      path: packages/common_crypto
  dbus: ^0.7.11
  decimal: ^3.0.2
  desktop_drop:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: ceca9081fbdccb2e3a71e32f9bfcc7b3e9c2b360
      path: packages/desktop_drop
  desktop_keep_screen_on: ^0.0.3
  desktop_webview_window: ^0.2.3
  device_info_plus: ^10.1.0
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  dio_compatibility_layer: ^0.1.0
  rhttp: ^0.11.1
  flutter_rust_bridge: ^2.6.0
  drift: ^2.26.1
  ecache: ^2.0.6
  emojis: ^0.9.9
  equatable: ^2.0.7
  file_picker: ^10.1.9
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.0
  file_selector_macos: ^0.9.3
  file_selector_windows: ^0.9.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_app_icon_badge: ^2.0.0
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_svg: ^2.1.0
  gal:
    git:
      url: https://github.com/boyan01/gal.git
      ref: b42e314284a09c9f0f9fe1e0e76e0c563402449e
  github: ^9.25.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  hooks_riverpod: ^2.5.1
  http: ^1.4.0
  http_client_helper: ^3.0.0
  hydrated_bloc: ^10.0.0
  image: ^4.5.4
  image_picker: ^1.0.5
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.4
  isolate: ^2.1.0
  json_annotation: ^4.8.1
  libsignal_protocol_dart: ^0.7.2
  local_auth: ^2.3.0
  lottie: ^3.1.2
  map: ^2.0.2
  markdown_widget: ^2.3.2+2
  mime: ^2.0.0
  mixin_bot_sdk_dart: ^1.3.1
  mixin_logger: ^0.1.2
  network_info_plus: ^6.1.4
  octo_image: ^2.0.0
  ogg_opus_player: ^0.7.0
  open_file: ^3.3.2
  overlay_support: ^2.1.0
  package_info_plus: ^8.3.0
  path: ^1.8.0
  path_provider: ^2.1.2
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_qr_code: ^3.4.0
  protocol_handler: ^0.2.0
  provider: ^6.1.5
  recase: ^4.1.0
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.5
  simple_animations: ^5.2.0
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.32
  stream_transform: ^2.1.1
  string_tokenizer:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      path: packages/string_tokenizer
      ref: 66a8ed5f955fa35c9aaac76842b9dab83c51db92
  super_clipboard: ^0.8.24
  super_context_menu: ^0.8.24
  super_native_extensions: ^0.8.24
  synchronized: ^3.3.1
  system_tray:
    path: third_party/system_tray
  ui_device:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 00654e51f51aa65cdc39784a3075c9abb8b9dd7c
      path: packages/ui_device
  ulid: ^2.0.0
  url_launcher: ^6.2.5
  uuid: ^4.5.1
  visibility_detector: ^0.4.0+2
  watcher: ^1.1.1
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.12.0
  win32: ^5.13.0
  win_toast: ^0.3.1
  window_manager: ^0.4.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 12decbe0f592e14e03223f6f2c0c7e0e2dbd70a1
  html: ^0.15.6
  video_player: ^2.9.5
  cupertino_icons: ^1.0.6
  video_compress: ^3.1.4
  webcrypto:
    git:
      url: https://github.com/boyan01/webcrypto.dart.git
      ref: 210839e1e9311bcddeb733297a565721692033ee
  hexagon: ^0.2.0
  breakpad_client: ^0.0.2
  data_detector:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 08c1ce40eb6abfad6049fb6aad8bd30312ec5319
      path: packages/data_detector
  envied: ^1.1.1
  sentry_flutter: ^8.14.2

dev_dependencies:
  build_runner: ^2.4.15
  debug_info_collector:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 77f03330001941f0ac303de6276dd2380f5bcc7e
      path: packages/debug_info_collector
  drift_dev: ^2.19.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  intl_utils: ^2.8.7
  json_serializable: ^6.7.1
  msix:
    git:
      url: https://github.com/riccardo-lomazzi/msix.git
      ref: 75190427070d1a57873cfd895fb9251d0713ebd8
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  envied_generator: ^1.1.0

dependency_overrides:
  very_good_analysis: ^7.0.0
  collection: ^1.18.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by https://github.com/fluttercandies/assets_generator
    # **************************************************************************

    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  # assets end

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: fonts/Noto-COLRv1.ttf
    - family: MixinCondensed
      fonts:
        - asset: fonts/mixin_font.otf

flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: false

analyzer:
  plugins:
    - moor

msix_config:
  display_name: Mixin Messenger
  publisher_display_name: Mixin Ltd
  identity_name: 14801MixinLtd.MixinDesktop
  publisher: CN=272248D5-9A62-44D7-A299-5E1F8B46A9B0
  msix_version: 0.38.0.0
  logo_path: ./assets/icons/windows_app_icon.png
  vs_generated_images_folder_path: ./dist/icons
  icons_background_color: transparent
  architecture: x64
  capabilities: "internetClient,microphone"
  store: true
  toast_activator:
    clsid: "94B64592-528D-48B4-B37B-C82D634F1BE7"
    arguments: "-ToastActivated"
    display_name: "Mixin Messenger"
