name: flutter_app
description: Mixin Messenger
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.35.4+0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  archive: ^3.1.2
  async: ^2.8.1
  bitsdojo_window: ^0.1.1+1
  bloc: ^8.0.3
  blurhash_dart: ^1.0.2
  decimal: ^2.2.0
  desktop_drop: ^0.3.3
  desktop_lifecycle: ^0.1.0
  desktop_webview_window: ^0.1.6
  device_info_plus: ^3.2.3
  dio: ^4.0.0
  drift: ^1.5.0
  ecache: ^2.0.1
  equatable: ^2.0.3
  extended_image: ^4.1.0
  file_picker: ^4.0.0
  file_selector: ^0.8.3
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.8.2+1
  file_selector_windows: ^0.8.2
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_app_icon_badge: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.0
  flutter_local_notifications: ^9.4.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_portal: ^1.1.0
  flutter_svg: ^1.0.3
  gallery_saver: ^2.3.2
  github: ^9.0.0
  hive: ^2.1.0
  hive_flutter: ^1.0.0
  http: ^0.13.3
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  isolate: ^2.1.0
  json_annotation: ^4.5.0
  libsignal_protocol_dart: ^0.5.6
  lottie: ^1.0.1
  map: ^1.0.0
  markdown: ^5.0.0
  mime: ^1.0.0
  mixin_bot_sdk_dart: ^0.2.14
  octo_image: ^1.0.0+1
  ogg_opus_player: ^0.3.1
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  pasteboard:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 7909b17640c06e9bf91b68e1e52105c3b16af284
      path: packages/pasteboard
  path: ^1.8.0
  path_provider: ^2.0.8
  photo_view:
    git:
      url: https://github.com/fireslime/photo_view.git
      ref: 52685ab7beaf8a9107904bdb8a1590924015d016
  pin_code_fields: ^7.4.0
  protocol_handler: ^0.1.2
  provider: ^6.0.1
  qr_flutter: ^4.0.0
  quick_breakpad:
    path: third_party/quick_breakpad
  recase: ^4.0.0
  rxdart: ^0.27.1
  scrollable_positioned_list: ^0.2.3
  sliver_tools: ^0.2.6
  sqlite3_flutter_libs: ^0.5.6
  stream_transform: ^2.0.0
  system_tray:
    path: third_party/system_tray
  tuple: ^2.0.0
  ulid: ^2.0.0
  url_launcher: ^6.1.2
  uuid: ^3.0.4
  very_good_analysis: ^2.1.1
  visibility_detector: ^0.2.2
  watcher: ^1.0.0
  web_socket_channel: ^2.2.0
  webview_flutter: ^3.0.1
  win32: ^2.5.2
  win_toast: ^0.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 57a2cd88486105d3d813583339eb0e23c9bfd6d2

dependency_overrides:
  bitsdojo_window_linux:
    git:
      url: https://github.com/MixinNetwork/bitsdojo_window.git
      ref: 78faaa6440c7fee146258bb0ef3336c33ed4555d
      path: bitsdojo_window_linux
  bitsdojo_window_windows:
    git:
      url: https://github.com/MixinNetwork/bitsdojo_window.git
      ref: 78faaa6440c7fee146258bb0ef3336c33ed4555d
      path: bitsdojo_window_windows

dev_dependencies:
  build_runner: any
  drift_dev: ^1.5.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  json_serializable: ^6.1.6
  msix: ^3.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # assets start

    # GENERATED CODE - DO NOT MODIFY MANUALLY
    # **************************************************************************
    # Auto generated by https://github.com/fluttercandies/assets_generator
    # **************************************************************************

    - assets/
    - assets/icons/
    - assets/images/

  # assets end
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: Localization
  use_deferred_loading: true

analyzer:
  plugins:
    - moor

msix_config:
  display_name: Mixin Desktop
  publisher_display_name: Mixin Ltd
  identity_name: 14801MixinLtd.MixinDesktop
  publisher: CN=272248D5-9A62-44D7-A299-5E1F8B46A9B0
  msix_version: 0.35.4.0
  logo_path: ./assets/icons/windows_app_icon.png
  vs_generated_images_folder_path: ./dist/icons
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,microphone'
  store: true
